### ISSUE TITLE
Please provide a README.md

### ISSUE THREAD

**Issue by oranja** [oh-my-fish/plugin-bak#4]
To make it easier to figure out:

1. What is the purpose of this plugin.
2. How it can be used.

**Comment by BarbzYHOOL** [comment]
I tried during 30 seconds

cpbak filename

Creates a backup filename.bak

Same with mvbak

uncpbak/unmvbak restores the file

**Comment by BarbzYHOOL** [comment]
I made it in a PR btw

**Comment by scorphus** [comment]
Thanks, @BarbzYHOOL
