### ISSUE TITLE
Sudo + cpbak not working

### ISSUE THREAD

**Issue by BarbzYHOOL** [oh-my-fish/plugin-bak#6]
I wanted to cpbak a system file but it said "permission erro"

So I used `sudo cpbak` and here is the output

"Impossible to create the symlink for file.bak"

`sudo cp` worked fine

Any idea somebody?

**Comment by BarbzYHOOL** [comment]
Same for mvbak :'(

But with "sudo -s" it works

**Comment by scorphus** [comment]
The plugin functions in, and only in, the namespace of the user. IWO that's expected.
